[package]
name = "nodekit-rs-video"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-next.workspace = true
mp4.workspace = true
nodekit-rs-response = { path = "../nodekit-rs-response" }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "bench"
harness = false