[package]
name = "nodekit-rs-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown.workspace = true
nodekit-rs-fb = { path = "../nodekit-rs-fb" }
paste.workspace = true
slotmap.workspace = true
url.workspace = true