[package]
name = "nodekit-rs-response"
version = "0.1.0"
edition = "2024"

[dependencies]
flatbuffers.workspace = true
nodekit-rs-fb = { path = "../nodekit-rs-fb" }
nodekit-rs-visual = { path = "../nodekit-rs-visual" }
pyo3.workspace = true
pyo3-stub-gen.workspace = true