[package]
name = "nodekit-rs-state"
version = "0.1.0"
edition = "2024"

[dependencies]
nodekit-rs-models = { path = "../nodekit-rs-models" }
pyo3.workspace = true
pyo3-stub-gen.workspace = true
slotmap.workspace = true
uuid.workspace = true