[package]
name = "nodekit-rs-asset"
version = "0.1.0"
edition = "2024"

[dependencies]
nodekit-rs-card = { path = "../nodekit-rs-card" }
reqwest.workspace = true
thiserror.workspace = true
url.workspace = true
zip.workspace = true 