[package]
name = "nodekit-rs-text"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
cosmic-text.workspace = true
markdown.workspace = true
thiserror.workspace = true

[dev-dependencies]
png.workspace = true