[package]
name = "nodekit-rs-node"
version = "0.1.0"
edition = "2024"

[dependencies]
blittle.workspace = true
nodekit-rs-board = { path = "../nodekit-rs-board" }
nodekit-rs-fb = { path = "../nodekit-rs-fb" }
reqwest.workspace = true
slotmap.workspace = true
url.workspace = true