[package]
name = "nodekit-rs-cursor"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
nodekit-rs-board = { path = "../nodekit-rs-board" }

[dev-dependencies]
png.workspace = true