[workspace]
members = [
    "nodekit-rs-audio",
    "nodekit-rs-client",
    "nodekit-rs-cursor",
    "nodekit-rs-fb",
    "nodekit-rs-graph",
    "nodekit-rs-image", "nodekit-rs-messages",
    "nodekit-rs-net",
    "nodekit-rs-response",
    "nodekit-rs-state",
    "nodekit-rs-video",
    "nodekit-rs-visual"
]

[package]
name = "nodekit-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
nodekit-rs-net = { path = "nodekit-rs-net" }
nodekit-rs-response = { path = "nodekit-rs-response" }
nodekit-rs-state = { path = "nodekit-rs-state" }
tokio.workspace = true

[workspace.dependencies]
async_zip = { version = "0.0.18",  features = ["deflate", "bzip2", "lzma", "zstd", "xz", "tokio"]}
async_zmq = "0.4.0"
blittle = "0.2.1"
bytes = "1.10.1"
bytemuck = "1.24.0"
clap = { version = "4.5.50", features = ["derive"] }
fast_image_resize = "5.3.0"
ffmpeg-next = "8.0.0"
flatbuffers = "25.9.23"
futures = "0.3.31"
hashbrown = "0.16.0"
hex_color = "3.0.0"
jpeg-decoder = "0.3.2"
png = "0.18.0"
pyo3 = { version = "0.27.1", features = ["experimental-inspect", "extension-module"] }
pyo3-stub-gen = "0.16.1"
regress = "0.10.4"
reqwest = "0.12.24"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
slotmap = "1.0.7"
tempdir = "0.3.7"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros", "fs"] }
uuid = { version = "1.18.1", features = ["v4"] }
url = "2.5.7"
