[workspace]
members = ["nodekit-rs-audio","nodekit-rs-cursor","nodekit-rs-image", "nodekit-rs-video", "nodekit-rs-visual"]

[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "nodekit_rs"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
blittle = "0.2.1"
bytemuck = "1.24.0"
fast_image_resize = "5.3.0"
ffmpeg-next = "8.0.0"
hex_color = "3.0.0"
png = "0.18.0"
pyo3 = { version = "0.27.1", features = ["experimental-inspect", "extension-module"] }
pyo3-stub-gen = "0.16.1"
thiserror = "2.0.17"

[dependencies]
blittle.workspace = true
hex_color.workspace = true
nodekit-rs-audio = { path = "nodekit-rs-audio" }
nodekit-rs-cursor = { path = "nodekit-rs-cursor" }
nodekit-rs-image = { path = "nodekit-rs-image" }
nodekit-rs-video = { path = "nodekit-rs-video" }
nodekit-rs-visual = { path = "nodekit-rs-visual" }
pyo3.workspace = true
pyo3-stub-gen.workspace = true
