[workspace]
members = [
    "nodekit-rs-image",
    "nodekit-rs-models", "nodekit-rs-png",
    "nodekit-rs-render", "nodekit-rs-card",
    "nodekit-rs-text",
    "nodekit-rs-video",
    "nodekit-rs-visual",
]

[package]
name = "nodekit-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "nodekit_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
nodekit-rs-card = { path = "nodekit-rs-card" }
nodekit-rs-models = { path = "nodekit-rs-models" }
nodekit-rs-render = { path = "nodekit-rs-render" }
pyo3.workspace = true
pyo3-stub-gen.workspace = true

[workspace.dependencies]
blittle = { version = "0.3.0", features = ["overlay"] }
bytemuck = "1.24.0"
cosmic-text = "0.15.0"
criterion = "0.7.0"
fast_image_resize = { version = "5.3.0", features = ["rayon"] }
hex_color = "3.0.0"
markdown = "1.0.0-alpha.24"
paste = "1.0.15"
png = "0.18.0"
pyo3 = { version = "0.27.1", features = ["experimental-inspect", "extension-module"] }
pyo3-stub-gen = { version = "0.17.0", default-features = false, features = ["either", "infer_signature", "ordered-float"] }
scuffle-ffmpeg = { version = "0.3.5", default-features = false, features = ["link_vcpkg_ffmpeg"] }
slotmap = "1.0.7"
thiserror = "2.0.17"
url = "2.5.7"
uuid = { version = "1.18.1", features = ["v4"] }
