[workspace]
members = [
    "nodekit-rs-client",
    "nodekit-rs-graph",
    "nodekit-rs-image",
    "nodekit-rs-models",
    "nodekit-rs-render",
    "nodekit-rs-request",
    "nodekit-rs-response",
    "nodekit-rs-socket",
    "nodekit-rs-state",
    "nodekit-rs-text",
    "nodekit-rs-video", "nodekit-rs-visual",
]

[package]
name = "nodekit-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
nodekit-rs-request = { path = "nodekit-rs-request" }
nodekit-rs-response = { path = "nodekit-rs-response" }
nodekit-rs-socket = { path = "nodekit-rs-socket" }
nodekit-rs-state = { path = "nodekit-rs-state" }

[workspace.dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
blittle = "0.2.1"
bytemuck = "1.24.0"
clap = { version = "4.5.50", features = ["derive"] }
cosmic-text = "0.15.0"
criterion = "0.7.0"
fast_image_resize = "5.3.0"
glam = { version = "0.30.9", features = ["serde"] }
hashbrown = "0.16.0"
hex_color = "3.0.0"
markdown = "1.0.0-alpha.24"
png = "0.18.0"
pyo3 = { version = "0.27.1", features = ["experimental-inspect", "extension-module"] }
pyo3-stub-gen = { version = "0.17.0", default-features = false, features = ["either", "infer_signature", "ordered-float"] }
regress = "0.10.4"
scuffle-ffmpeg = { version = "0.3.5", default-features = false, features = ["link_vcpkg_ffmpeg"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
slotmap = "1.0.7"
thiserror = "2.0.17"
zmq = "0.10.0"
