[workspace]
members = ["nodekit-rs-board", "nodekit-rs-download","nodekit-rs-fb", "nodekit-rs-graph", "nodekit-rs-video"]

[package]
name = "nodekit-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
blittle.workspace = true
ffmpeg-next.workspace = true

[workspace.dependencies]
blittle = "0.2.0"
bytes = "1.10.1"
ffmpeg-next = "8.0.0"
flatbuffers = "25.9.23"
futures = "0.3.31"
hashbrown = "0.16.0"
jpeg-decoder = "0.3.2"
paste = "1.0.15"
reqwest = "0.12.24"
sha2 = "0.10.9"
slotmap = "1.0.7"
tempdir = "0.3.7"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["rt", "macros"] }
uuid = { version = "1.18.1", features = ["v4"] }
url = "2.5.7"
