[package]
name = "nodekit-rs-models"
version = "0.1.0"
edition = "2024"

[dependencies]
glam.workspace = true
pyo3.workspace = true
pyo3-stub-gen.workspace = true
slotmap.workspace = true

[lib]
name = "nodekit_rs_models"
crate-type = ["cdylib", "rlib"]