site_name: NodeKit

nav:
  - Home: index.md
  - Install: installation.md
  - Getting started: 'getting-started.md'
  - API: api/index.md
  - Notes:
      - EFSM: efsm.md
      - Markdown: markdown.md

repo_url: https://github.com/intelligence-observatory/nodekit

theme:
  name: material
  font:
    text: Inter
  logo: nodekit-logo.svg
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.instant        # no full page reloads
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections       # grouped sections in sidebar
    - navigation.tracking       # URL updates as you scroll
    - content.code.copy         # copy button on code blocks
    - toc.integrate             # move local TOC into sidebar

  palette:
    - scheme: default         # light
      primary: grey           # primary color
      accent: blue grey          # accent color


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]                     # allow imports from repo root
          options:
            docstring_style: google        # or "numpy" / "sphinx"
            merge_init_into_class: true    # __init__ params appear on the class
            show_source: true             # hide "view source" links (optional)
watch:
  - ../nodekit
extra:
  generator: false   # hides the "Made with Material for MkDocs" text
