site_name: NodeKit


nav:
  - Home: index.md
  - Install: installation.md
  - Getting started: 'getting-started.md'
  - API:
      - Python reference: api/python.md


theme:
  name: material
  font:
    text: Inter

  language: en
  features:
    - navigation.instant        # no full page reloads
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections       # grouped sections in sidebar
    - navigation.tracking       # URL updates as you scroll
    - content.code.copy         # copy button on code blocks
    - toc.integrate             # move local TOC into sidebar

  palette:
    - scheme: default         # light
      primary: grey           # primary color
      accent: amber          # accent color
      toggle:
        icon: material/brightness-4
        name: Switch to Dark Mode
    - scheme: slate           # dark
      primary: grey
      accent: amber
      toggle:
        icon: material/brightness-6
        name: Switch to Dark Mode
