site_name: NodeKit

nav:
  - Home: index.md
  - Tutorial:
      - 1. Install NodeKit: 'tutorial/1-installation.md'
      - 2. Write your first Graph: 'tutorial/2-first-graph.md'
      - 3. Write your second Graph: 'tutorial/2b-afc-graph.md'
      - 4. Get behavioral data: 'tutorial/3-deploy-graph.md'
      - What's left to learn?: 'tutorial/whats-next.md'
  - Guides:
      - Deploy to Mechanical Turk or Prolific: 'guides/mechanical-turk-and-prolific.md'
      - Saving and sharing Graphs and Traces: 'guides/saving-and-sharing.md'
      - Format TextCards using Markdown: 'guides/styling-text.md'
      - Add time limits to Nodes: 'guides/adding-time-limits.md'
      - Write your own Agent: 'guides/writing-agents.md'
  - Concepts:
      - Board coordinate system: concepts/board-coordinate-system.md
  - API Reference:
      - Node: reference/node.md
      - Graph: reference/graph.md
      - Trace: reference/trace.md
      - Agents: reference/agent.md
      - Cards: reference/cards.md
      - Sensors: reference/sensors.md
      - Actions: reference/actions.md
      - Transitions: reference/transitions.md
      - Events: reference/events.md
      - Expressions: reference/expressions.md
      - Assets: reference/assets.md
      - Values: reference/values.md
      - Ops: reference/ops.md
      - Site: reference/site.md
  - Examples:
      - Overview: examples/index.md



repo_url: https://github.com/intelligence-observatory/nodekit

theme:
  name: material
  font:
    text: Inter
  logo: nodekit-logo.svg
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.instant        # no full page reloads
    - navigation.tracking       # URL updates as you scroll
    - navigation.footer
    - content.code.copy         # copy button on code blocks
    - content.tabs             # tabbed content

  palette:
    - scheme: default         # light
      primary: grey           # primary color
      accent: blue grey          # accent color

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: "1-3"
plugins:
  - search
  - mkdocstrings:
      handlers:
        python: # https://mkdocstrings.github.io/python/usage/#recommended-settings
          inventories:
            - https://docs.python.org/3.12/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          paths: [ ".." ]                     # allow imports from repo root
          options:
            modernize_annotations: true
            docstring_style: google        # or "numpy" / "sphinx"
            docstring_section_style: list
            parameter_headings: false
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true    # __init__ params appear on the class
            show_source: false             # hide "view source" links (optional)
            show_root_heading: true
            show_root_full_path: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            heading_level: 3
            show_bases: false
            extensions:
              - griffe_pydantic:
                  schema: false # Reactivate
watch:
  - ../nodekit
extra:
  generator: false   # hides the "Made with Material for MkDocs" text

extra_css:
  - styles/mkdocstrings.css
