site_name: NodeKit

nav:
  - Home: index.md
  - Tutorial: 'getting-started.md' # Tutorial
  - Concepts: #  Explanation
      - EFSM: efsm.md
      - Markdown: markdown.md
  - How-to guides: # Recipes
      - Mechanical Turk: 'deployment/mechanical-turk.md'
  - API:  # Reference
      - Node: api/node.md
      - Graph: api/graph.md
      - Trace: api/trace.md
      - Ops: api/ops.md
      - Expressions: api/expressions.md


repo_url: https://github.com/intelligence-observatory/nodekit

theme:
  name: material
  font:
    text: Inter
  logo: nodekit-logo.svg
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.instant        # no full page reloads
    - navigation.tracking       # URL updates as you scroll
    - content.code.copy         # copy button on code blocks
    - toc.integrate             # move local TOC into sidebar

  palette:
    - scheme: default         # light
      primary: grey           # primary color
      accent: blue grey          # accent color


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]                     # allow imports from repo root
          options:
            docstring_style: google        # or "numpy" / "sphinx"
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true    # __init__ params appear on the class
            show_source: true             # hide "view source" links (optional)
            show_root_heading: true
            show_root_full_path: true
            heading_level: 3
            extensions:
              - griffe_pydantic:
                  schema: true
watch:
  - ../nodekit
extra:
  generator: false   # hides the "Made with Material for MkDocs" text
