[package]
name = "nodekit-rs-image"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
nodekit-rs-response = { path = "../nodekit-rs-response" }
png.workspace = true
thiserror.workspace = true