[package]
name = "nodekit-rs-image"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
nodekit-rs-board = { path = "../nodekit-rs-board" }
png.workspace = true
thiserror.workspace = true