[package]
name = "nodekit-rs-image"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
nodekit-rs-models = { path = "../nodekit-rs-models" }
nodekit-rs-visual = { path = "../nodekit-rs-visual" }
png.workspace = true
thiserror.workspace = true