on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - nodekit/**.py
      - .github/workflows/ty.yaml
jobs:
  ty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install uv
        run: |
          pip3 install uv
          uv venv
          source .venv/bin/activate
      - name: Install nodekit
        run: |
          uv pip install -e .
      - name: Type check
        run: |
          make check